AC_DEFUN([CLBS_TEST_SUPPORT], [
    AC_MSG_NOTICE([Enabling test support])
    CLBS_BOOST_TEST([HAS_TEST_SUPPORT=1], [
        HAS_TEST_SUPPORT=0 
        AC_MSG_ERROR([Cannot enable test support])]
    )
    AC_SUBST(HAS_TEST_SUPPORT)

    CLBS_TEST_CPPFLAGS=$BOOST_TEST_CPPFLAGS
    CLBS_TEST_LDFLAGS=$BOOST_TEST_LDFLAGS
    AC_SUBST(CLBS_TEST_CPPFLAGS)
    AC_SUBST(CLBS_TEST_LDFLAGS)
])

